#!/usr/bin/env node
/**
 * Turn one or more `collect.js` captures into a versioned TypeScript module in an instance.
 *
 *   node write.mjs --release 26.4.1-build10569 --out typescript/src/generated capture*.json
 *
 * Captures merge: a page can only report the components it renders, so sweeping several stock
 * pages and merging is the normal way to use this. Later files win on conflict, except
 * `classes` and `tokens`, which union.
 *
 * The output is stamped with the release it came from. Regenerating after an instance upgrade
 * rewrites the same file, so `git diff` shows exactly what the platform changed — which is the
 * point of versioning it at all.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';

function parseArgs(argv) {
    const args = { files: [], out: 'typescript/src/generated', release: null };
    for (let i = 0; i < argv.length; i += 1) {
        const a = argv[i];
        if (a === '--release') { args.release = argv[++i]; continue; }
        if (a === '--out') { args.out = argv[++i]; continue; }
        if (a === '--help' || a === '-h') { args.help = true; continue; }
        args.files.push(a);
    }
    return args;
}

const args = parseArgs(process.argv.slice(2));

if (args.help || args.files.length === 0) {
    console.error(`usage: node write.mjs --release <release> [--out <dir>] <capture.json>...

  --release   the release the instance serves, e.g. 26.4.1-build10569.
              \`aspenup update\` prints it; it is NOT the SDK version.
  --out       directory to write into (default typescript/src/generated)

Captures come from running collect.js on signed-in pages of that instance.`);
    process.exit(args.help ? 0 : 1);
}

if (!args.release) {
    console.error('error: --release is required. Without it the output claims to describe an\n'
        + '       instance it cannot name, which is worse than not generating it.');
    process.exit(1);
}

const merged = { classes: new Set(), tokens: {}, recipes: {}, icons: {}, sources: [] };

for (const file of args.files) {
    let capture;
    try {
        capture = JSON.parse(readFileSync(file, 'utf8'));
    } catch (error) {
        console.error(`error: could not read ${file}: ${error.message}`);
        process.exit(1);
    }
    for (const c of capture.classes ?? []) merged.classes.add(c);
    Object.assign(merged.tokens, capture.tokens ?? {});
    for (const [k, v] of Object.entries(capture.recipes ?? {})) merged.recipes[k] ??= v;
    for (const [k, v] of Object.entries(capture.icons ?? {})) merged.icons[k] ??= v;
    merged.sources.push({ file, url: capture.url ?? null, capturedAt: capture.capturedAt ?? null });
}

const emptyTokens = Object.entries(merged.tokens).filter(([, v]) => v === '').map(([k]) => k);

const lit = (v) => JSON.stringify(v);
const classes = [...merged.classes].sort();

const body = `/**
 * GENERATED by the aspen-design-system harvester. Do not edit by hand.
 *
 * Harvested from the running instance, release ${args.release}.
 * Regenerate after an upgrade; the diff is the platform's change log.
 *
 * Sources:
${merged.sources.map((s) => ` *   ${s.url ?? s.file}${s.capturedAt ? `  (${s.capturedAt})` : ''}`).join('\n')}
 *
 * What this is for: nothing validates a Tailwind class name or an \`--ap-*\` token name at
 * build time, and a wrong one fails *silently* — the class matches no rule, or \`var()\` falls
 * back to nothing. \`check.mjs\` diffs the source tree against the sets below so those become
 * build errors instead of a rendering mystery.
 */

/** The release this was harvested from. */
export const RELEASE = ${lit(args.release)};

/** Every class name the instance's stylesheet defines a rule for. */
export const CLASSES: ReadonlySet<string> = new Set(${lit(classes)});

/** Every \`--ap-*\` custom property and the value it resolves to on :root. */
export const TOKENS: Readonly<Record<string, string>> = ${JSON.stringify(merged.tokens, null, 4)};

/**
 * The class string of each design-system component the harvested pages rendered, keyed by the
 * \`data-slot\` or \`group/<name>\` marker that identified it.
 *
 * These are observed renderings, not the design system's source recipes — only components the
 * harvested pages actually render appear here, and a component can render differently in a
 * different context. Treat them as evidence, not as a complete catalogue.
 */
export const RECIPES = ${JSON.stringify(merged.recipes, null, 4)} as const;

/**
 * Icon path data observed in rendered SVGs, keyed by a hash of the path.
 *
 * Names are not in the DOM, so each entry carries whatever hint was available. Rename them as
 * you identify them — an emoji or a text glyph substitute ignores \`currentColor\` and renders
 * in an arbitrary font, so the real path is the only faithful option.
 */
export const ICONS = ${JSON.stringify(merged.icons, null, 4)} as const;
`;

mkdirSync(args.out, { recursive: true });
const target = join(args.out, 'design-system.ts');
writeFileSync(target, body);

console.log(`wrote ${target}`);
console.log(`  release  ${args.release}`);
console.log(`  classes  ${classes.length}`);
console.log(`  tokens   ${Object.keys(merged.tokens).length}${emptyTokens.length ? ` (${emptyTokens.length} resolve to empty)` : ''}`);
console.log(`  recipes  ${Object.keys(merged.recipes).length}`);
console.log(`  icons    ${Object.keys(merged.icons).length}`);
console.log(`  from     ${merged.sources.length} capture(s)`);
if (emptyTokens.length) {
    console.log(`\nTokens defined but resolving to empty (usually theme-conditional):`);
    for (const t of emptyTokens.slice(0, 10)) console.log(`  ${t}`);
    if (emptyTokens.length > 10) console.log(`  … and ${emptyTokens.length - 10} more`);
}
